name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test:unit
  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: npm install && npm run make
      - uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-lib
          path: out/make/zip/darwin/arm64/Host Genius-darwin-arm64-1.0.0.zip
  test-e2e:
    timeout-minutes: 10
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install && npm i lightningcss-win32-x64-msvc
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Create Executable
        run: npm run make
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
