name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test:unit

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install dependencies
        run: |
          npm install
          npm install lightningcss-darwin-arm64
          npm install @tailwindcss/oxide-darwin-arm64
      - name: Rebuild native modules
        run: npm run rebuild
      - name: Build
        run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-lib
          path: out/make/Host Genius-darwin-1.0.0-arm64.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          npm install
          npm install lightningcss-win32-x64-msvc
          npm install @tailwindcss/oxide-win32-x64-msvc
      - name: Rebuild native modules
        run: npm run rebuild
      - name: Build
        run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          name: windows-x64-lib
          path: out/make/squirrel.windows/x64/Host Genius-1.0.0 Setup.exe

  test-e2e:
    timeout-minutes: 10
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          npm install
          npm install lightningcss-win32-x64-msvc
          npm install @tailwindcss/oxide-win32-x64-msvc
      - name: Rebuild native modules
        run: npm run rebuild
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Create Executable
        run: npm run make
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
